# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'de678d69-ebdc-406b-91dc-38b6fe7693e1'
  imageRepository: 'kanchannetherlandsgitopspracticedevsecopssonarqube'
  containerRegistry: 'acr1986.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Docker@2
      displayName: Build 
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
       
- stage: Test
  displayName: test
  dependsOn: Build
  jobs:
  - job: Test
    displayName: Test

    steps:
    - task: VSTest@2
      timeoutInMinutes: 0
       
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\bin\**\*test.dll
          **\bin\**\*tests.dll
        searchFolder: '$(System.DefaultWorkingDirectory)' 

- 