apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermariogame-deployment
  labels:
    app: supermariogame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermariogame
  template:
    metadata:
      labels:
        app: supermariogame
    spec:
      containers:
       - name: supermariogame-container
         image: acr19860.azurecr.io/dockermariogame:14
          ports: 
           - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: supermariogame-service
spec:
  selector:
    app: supermariogame
  ports:
  - protocol: TCP
    port: 8600  # Change this line to your desired external port
    targetPort: 8080
  type: LoadBalancer

